---
name: Pack
description: Pack plugin and upload artifact
inputs:
  node-version:
    description: Node.js version
    required: true
    default: 18
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup local Turbo cache
      uses: dtinth/setup-github-actions-caching-for-turbo@cc723b4600e40a6b8815b65701d8614b91e2669e # v1

    - name: Run the pack script
      id: run-export-dynamic
      shell: bash
      working-directory: ${{ github.workspace }}
      run:
        ${{ github.action_path }}/pack.sh

    - name: Check if the packages exists
      shell: bash
      working-directory: ${{ github.workspace }}
      run:
        ls -la ${{ github.workspace }}/ansible-plugins-pack

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ansible-plugins-backstage-rhaap
        path: ${{ github.workspace }}/ansible-plugins-pack/
        if-no-files-found: error
        retention-days: 1
        overwrite: true

    - name: Release and add to GH UI
      uses: softprops/action-gh-release@v2
      with:
        body:
          Backstage/Ansible Dynamic Plugins, for Red Hat Developer Hub
        files: ${{ github.workspace }}/ansible-plugins-pack/*
        repository: ${{ github.repository }}
