---
name: Pack-artifact
description: Pack plugin and upload artifact
inputs:
  plugin:
    description: Name of the plugin to build
    required: true
    default: ""
  node-version:
    description: Node.js version
    required: true
    default: 18
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup local Turbo cache
      uses: dtinth/setup-github-actions-caching-for-turbo@a0e976d970c2a94366a26984efcef3030e2c0115 # v1

    - name: Create archive destination folder
      shell: bash
      run:
        mkdir -p ${{ github.workspace }}/dynamic-plugins-archives

    - name: Install dependencies for - ansible frontend-plugin
      shell: bash
      working-directory: plugins/ansible
      run: |
        yarn install
        if [[ $(git diff --name-only . || true) ]]; then
          echo "After 'yarn install', workspace is dirty! The following files have changed:"
          echo
          git diff --name-only . || true
          exit 42
        fi

    - name: Build - ${{ inputs.plugin }}
      shell: bash
      working-directory: plugins/ansible
      run: |
        yarn tsc
        yarn build

    - name: Pack - ${{ inputs.plugin }}
      shell: bash
      working-directory: plugins/ansible
      run: |
        npm pack --pack-destination ${{ github.workspace }}/dynamic-plugins-archives

    # - name: Get package name from package.json
    #   shell: bash
    #   working-directory: ${{ inputs.plugin }}
    #   run: |
    #     package_name=$(jq -r '.name' package.json | sed 's/@//' | tr '/' '-')
    #     package_version=$(jq -r '.version' package.json)
    #     pack_artifact_name="${package_name}-${package_version}.tgz"
    #     echo "Package name: $pack_artifact_name"
    #     echo "::set-output name=pack_artifact_name::$pack_artifact_name"

    # - name: Upload artifact for deployment job
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: $PACK_NAME
    #     path: $PACK_PATH
    #   env:
    #     PACK_NAME: ${{ steps.set_var.outputs.pack_artifact_name }}
    #     PACK_PATH: ${{ inputs.plugin }}/${{ steps.set_var.outputs.pack_artifact_name }}

    - uses: actions/upload-artifact@v4
      with:
          name: dynamic plugin packages
          path: ${{ github.workspace }}/dynamic-plugins-archives/
          if-no-files-found: error
          retention-days: 1
          overwrite: true

    - name: Check error code
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('The export failed for the following plugins: ' + '${{ steps.export-dynamic.outputs.ERRORS }}')

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          body:
            Dynamic Plugins (for Red Hat Developer Hub) built from the ${{ steps.set-env-vars.outputs.BACKSTAGE_RELEASE }} release of Backstage.
          files: ${{ github.workspace }}/dynamic-plugins-archives/*
          repository: ${{ github.repository }}
