# Use Red Hat Universal Base Image (UBI) for certification compliance
FROM registry.access.redhat.com/ubi9/nodejs-22:9.6-1753172464
USER root

# Required labels for Red Hat certification
LABEL name="ansible-backstage-plugins" \
      vendor="Red Hat, Inc." \
      version="1.5.0" \
      release="1" \
      summary="Red Hat Developer Hub Ansible Backstage Dynamic Plugins" \
      description="Dynamic plugins collection for Red Hat Developer Hub (RHDH) providing Ansible automation capabilities, authentication, catalog management, and scaffolding functionality." \
      maintainer="Red Hat Ansible Team <ansible-team@redhat.com>" \
      io.k8s.description="Red Hat Developer Hub Ansible Backstage Dynamic Plugins" \
      io.k8s.display-name="RHDH Ansible Dynamic Plugins" \
      io.openshift.tags="ansible,backstage,rhdh,automation,dynamic-plugins" \
      com.redhat.component="ansible-backstage-plugins" \
      distribution-scope="public" \
      url="https://github.com/ansible/ansible-backstage-plugins/" \
      vcs-ref="main" \
      vcs-type="git"

# Copy dynamic plugins
COPY . .

# Add license information for certification compliance
COPY LICENSE /licenses/

# Switch to non-root user for security compliance
USER 1001
