dynamicPlugins:
  backend:
    janus-idp.backstage-plugin-scaffolder-backend-module-ansible:
      mountPoints:
        - importName: createAnsibleContentAction
          mountPoint: entity.page.overview/cards
catalog:
  locations:
    - type: file
      target: ../../dynamic-plugins-root/scaffolder-backend-module-ansible/templates/all.yaml
      rules:
        - allow: [Template]
ansible:
  devSpacesBaseUrl: "https://devspaces.apps.ansible-rhdh.testing.ansible.com/#https://github.com/"
  baseUrl: "localhost"
  port: 5000
