---
name: Release / plugins
on:
  workflow_dispatch:
    inputs:
      node-version:
        description: node-version to execute the export
        required: false
        default: '18.x'
  push:
    tags: ["v*.*.*"]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=8192
    permissions:
      contents: write

    name: 🚀 / release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: DEBUG - Show GitHub ref tag
        run: echo "${GITHUB_REF##*/}"

      - name: DEBUG - Show GitHub ref tag only version
        run: echo "${GITHUB_REF##*/v}"

      - name: Package plugins
        uses: ./.github/actions/pack
        with:
          node-version: ${{ inputs.node-version }}

      - name: Check if the packages exists
        shell: bash
        run: ls -la ${{ github.workspace }}/ansible-plugins-pack

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ansible-plugins-backstage-rhaap
          path: ${{ github.workspace }}/ansible-plugins-pack/
          if-no-files-found: error
          retention-days: 1
          overwrite: true

      - name: Add artifacts to GH UI
        uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: ${{ github.workspace }}/ansible-plugins-pack/*
